apiVersion: v1
kind: Service
metadata:
  name: {{ include "traefik.fullname" . }}
  labels:
    {{- include "traefik.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "NodePort" }}
  selector:
    {{- include "traefik.selectorLabels" . | nindent 4 }}
  ports:
    - name: web
      port: {{ int .Values.service.port }}
      targetPort: web
      protocol: TCP
      {{- with include "traefik.nodePort" . }}
      {{- if ne $.Values.service.type "ClusterIP" }}
      nodePort: {{ . }}
      {{- end }}
      {{- end }}
